import { describe, expect, it } from "vitest";
import type { Ir } from "@perchjs/core";
import { emitIr } from "./emit.js";
import { readOptionsOf } from "./options.js";
import { readDmmf } from "./dmmf-reader.js";
import { FIXTURE_DMMF } from "./__fixtures__/dmmf.js";

describe("what the generator writes", () => {
  const source = emitIr(readDmmf(FIXTURE_DMMF));

  it("names the type, so a malformed IR fails a typecheck", () => {
    expect(source).toContain('import type { Ir } from "@perchjs/prisma";');
    expect(source).toContain("export const IR: Ir = {");
  });

  it("says not to edit it, and how to change it", () => {
    expect(source.startsWith("// Generated by @perchjs/prisma-generator")).toBe(true);
    expect(source).toContain("prisma generate");
  });

  it("indents, so a diff shows which field moved", () => {
    // One line would make the file unreviewable, and `labelField` is what
    // search reaches — a change to it has to be visible in a pull request.
    expect(source).toContain('\n      "labelField": "name"');
  });

  it("round-trips the IR it was given", () => {
    const ir = readDmmf(FIXTURE_DMMF);
    const body = source.slice(source.indexOf("= {") + 2, source.lastIndexOf(";"));

    expect(JSON.parse(body) as Ir).toEqual(ir);
  });
});

describe("the soft-delete lists a generator block can carry", () => {
  it("asks for nothing when neither is declared", () => {
    expect(readOptionsOf({})).toEqual({});
  });

  it("reads a lone string as a list of one", () => {
    // A generator block writes `softDelete = "Audit"` as readily as a list.
    expect(readOptionsOf({ softDelete: "Audit" })).toEqual({
      softDelete: { Audit: true },
    });
  });

  it("turns the two lists into the one map the reader takes", () => {
    expect(
      readOptionsOf({ softDelete: ["Audit"], noSoftDelete: ["Post", "Tag"] }),
    ).toEqual({ softDelete: { Audit: true, Post: false, Tag: false } });
  });

  it("lets the explicit list win when a model is in both", () => {
    expect(readOptionsOf({ softDelete: ["Post"], noSoftDelete: ["Post"] })).toEqual({
      softDelete: { Post: true },
    });
  });

  it("ignores what is neither a string nor a list of them", () => {
    expect(readOptionsOf({ softDelete: 7, noSoftDelete: [1, "Post", null] })).toEqual({
      softDelete: { Post: false },
    });
  });
});
