import type { Ir } from "@perchjs/core";

/**
 * The IR as a TypeScript module: annotated rather than inferred, so a malformed
 * one fails a typecheck instead of the first query, and indented so a diff shows
 * which field moved.
 *
 * The type comes from `@perchjs/prisma` because that is what the consumer
 * installed — a generated file must not import a package they never declared.
 */
export function emitIr(ir: Ir): string {
  return `${HEADER}import type { Ir } from "@perchjs/prisma";

export const IR: Ir = ${JSON.stringify(ir, null, 2)};
`;
}

const HEADER = `// Generated by @perchjs/prisma-generator. Do not edit.
//
// Re-run \`prisma generate\` after changing schema.prisma. Check this file in:
// it is the metadata the panel is built from, and a diff is how a change to it
// gets reviewed.

`;
